<Project>
  <PropertyGroup Condition="'$(MSBuildProjectName)' == 'Reimaginate.DataHub.Agent.BusinessCentral.Abstractions'">
    <VersionPrefix>1.0.0-beta.3</VersionPrefix>
  </PropertyGroup>
  <PropertyGroup Condition="'$(MSBuildProjectName)' == 'Reimaginate.DataHub.Agent.BusinessCentral'">
    <VersionPrefix>1.0.0-beta.3</VersionPrefix>
  </PropertyGroup>
  <PropertyGroup Condition="'$(MSBuildProjectName)' == 'Reimaginate.DataHub.Agent.TestFramework.BusinessCentral'">
    <VersionPrefix>1.0.0-beta.3</VersionPrefix>
  </PropertyGroup>
  <ItemGroup>
    <DataHubAgentPublicPackage Include="Reimaginate.DataHub.Agent.BusinessCentral.Abstractions">
      <ProjectPath>src\Reimaginate.DataHub.Agent.BusinessCentral.Abstractions\Reimaginate.DataHub.Agent.BusinessCentral.Abstractions.csproj</ProjectPath>
      <Version>1.0.0-beta.3</Version>
      <Family>businesscentral</Family>
      <ReleaseEnabled>true</ReleaseEnabled>
      <PublicRepository>https://github.com/Reimaginate/DataHub.Agent.BusinessCentral</PublicRepository>
    </DataHubAgentPublicPackage>
    <DataHubAgentPublicPackage Include="Reimaginate.DataHub.Agent.BusinessCentral">
      <ProjectPath>src\Reimaginate.DataHub.Agent.BusinessCentral\Reimaginate.DataHub.Agent.BusinessCentral.csproj</ProjectPath>
      <Version>1.0.0-beta.3</Version>
      <Family>businesscentral</Family>
      <ReleaseEnabled>true</ReleaseEnabled>
      <PublicRepository>https://github.com/Reimaginate/DataHub.Agent.BusinessCentral</PublicRepository>
    </DataHubAgentPublicPackage>
    <DataHubAgentPublicPackage Include="Reimaginate.DataHub.Agent.TestFramework.BusinessCentral">
      <ProjectPath>src\Reimaginate.DataHub.Agent.TestFramework.BusinessCentral\Reimaginate.DataHub.Agent.TestFramework.BusinessCentral.csproj</ProjectPath>
      <Version>1.0.0-beta.3</Version>
      <Family>businesscentral</Family>
      <ReleaseEnabled>true</ReleaseEnabled>
      <PublicRepository>https://github.com/Reimaginate/DataHub.Agent.BusinessCentral</PublicRepository>
    </DataHubAgentPublicPackage>
  </ItemGroup>
</Project>
